enchant-disable-worlds:
- ''
ce-item-material-whitelist:
- 'ALL_ARMOR'
- 'ALL_SWORD'
- 'ALL_AXE'
- 'ALL_HOE'
- 'ALL_PICKAXE'
- 'ALL_AXE'
- 'ALL_SHOVEL'
- 'ALL_SHOVEL'
- 'ALL_BOW'
- 'SHIELD'
entity-group:
  ALL:
  - 'DROPPED_ITEM'
  - 'EXPERIENCE_ORB'
  - 'AREA_EFFECT_CLOUD'
  - 'ELDER_GUARDIAN'
  - 'WITHER_SKELETON'
  - 'STRAY'
  - 'EGG'
  - 'LEASH_HITCH'
  - 'PAINTING'
  - 'ARROW'
  - 'SNOWBALL'
  - 'FIREBALL'
  - 'SMALL_FIREBALL'
  - 'ENDER_PEARL'
  - 'ENDER_SIGNAL'
  - 'SPLASH_POTION'
  - 'THROWN_EXP_BOTTLE'
  - 'ITEM_FRAME'
  - 'WITHER_SKULL'
  - 'PRIMED_TNT'
  - 'FALLING_BLOCK'
  - 'FIREWORK'
  - 'HUSK'
  - 'SPECTRAL_ARROW'
  - 'SHULKER_BULLET'
  - 'DRAGON_FIREBALL'
  - 'ZOMBIE_VILLAGER'
  - 'SKELETON_HORSE'
  - 'ZOMBIE_HORSE'
  - 'ARMOR_STAND'
  - 'DONKEY'
  - 'MULE'
  - 'EVOKER_FANGS'
  - 'EVOKER'
  - 'VEX'
  - 'VINDICATOR'
  - 'ILLUSIONER'
  - 'MINECART_COMMAND'
  - 'BOAT'
  - 'MINECART'
  - 'MINECART_CHEST'
  - 'MINECART_FURNACE'
  - 'MINECART_TNT'
  - 'MINECART_HOPPER'
  - 'MINECART_MOB_SPAWNER'
  - 'CREEPER'
  - 'SKELETON'
  - 'SPIDER'
  - 'GIANT'
  - 'ZOMBIE'
  - 'SLIME'
  - 'GHAST'
  - 'ZOMBIFIED_PIGLIN'
  - 'ENDERMAN'
  - 'CAVE_SPIDER'
  - 'SILVERFISH'
  - 'BLAZE'
  - 'MAGMA_CUBE'
  - 'ENDER_DRAGON'
  - 'WITHER'
  - 'BAT'
  - 'WITCH'
  - 'ENDERMITE'
  - 'GUARDIAN'
  - 'SHULKER'
  - 'PIG'
  - 'SHEEP'
  - 'COW'
  - 'CHICKEN'
  - 'SQUID'
  - 'WOLF'
  - 'MUSHROOM_COW'
  - 'SNOWMAN'
  - 'OCELOT'
  - 'IRON_GOLEM'
  - 'HORSE'
  - 'RABBIT'
  - 'POLAR_BEAR'
  - 'LLAMA'
  - 'LLAMA_SPIT'
  - 'PARROT'
  - 'VILLAGER'
  - 'ENDER_CRYSTAL'
  - 'TURTLE'
  - 'PHANTOM'
  - 'TRIDENT'
  - 'COD'
  - 'SALMON'
  - 'PUFFERFISH'
  - 'TROPICAL_FISH'
  - 'DROWNED'
  - 'DOLPHIN'
  - 'CAT'
  - 'PANDA'
  - 'PILLAGER'
  - 'RAVAGER'
  - 'TRADER_LLAMA'
  - 'WANDERING_TRADER'
  - 'FOX'
  - 'BEE'
  - 'HOGLIN'
  - 'PIGLIN'
  - 'STRIDER'
  - 'ZOGLIN'
  - 'PIGLIN_BRUTE'
  - 'FISHING_HOOK'
  - 'LIGHTNING'
  - 'PLAYER'
  - 'UNKNOWN'
  MOB:
  - 'ELDER_GUARDIAN'
  - 'WITHER_SKELETON'
  - 'STRAY'
  - 'HUSK'
  - 'ZOMBIE_VILLAGER'
  - 'SKELETON_HORSE'
  - 'ZOMBIE_HORSE'
  - 'DONKEY'
  - 'MULE'
  - 'EVOKER'
  - 'VEX'
  - 'VINDICATOR'
  - 'ILLUSIONER'
  - 'CREEPER'
  - 'SKELETON'
  - 'SPIDER'
  - 'GIANT'
  - 'ZOMBIE'
  - 'SLIME'
  - 'GHAST'
  - 'ZOMBIFIED_PIGLIN'
  - 'ENDERMAN'
  - 'CAVE_SPIDER'
  - 'SILVERFISH'
  - 'BLAZE'
  - 'MAGMA_CUBE'
  - 'ENDER_DRAGON'
  - 'WITHER'
  - 'BAT'
  - 'WITCH'
  - 'ENDERMITE'
  - 'GUARDIAN'
  - 'SHULKER'
  - 'PIG'
  - 'SHEEP'
  - 'COW'
  - 'CHICKEN'
  - 'SQUID'
  - 'WOLF'
  - 'MUSHROOM_COW'
  - 'SNOWMAN'
  - 'OCELOT'
  - 'IRON_GOLEM'
  - 'HORSE'
  - 'RABBIT'
  - 'POLAR_BEAR'
  - 'LLAMA'
  - 'PARROT'
  - 'VILLAGER'
  - 'TURTLE'
  - 'PHANTOM'
  - 'COD'
  - 'SALMON'
  - 'PUFFERFISH'
  - 'TROPICAL_FISH'
  - 'DROWNED'
  - 'DOLPHIN'
  - 'CAT'
  - 'PANDA'
  - 'PILLAGER'
  - 'RAVAGER'
  - 'TRADER_LLAMA'
  - 'WANDERING_TRADER'
  - 'FOX'
  - 'BEE'
  - 'HOGLIN'
  - 'PIGLIN'
  - 'STRIDER'
  - 'ZOGLIN'
  - 'PIGLIN_BRUTE'
material-group:
  ALL_ORE_BLOCK:
  - 'GOLD_ORE'
  - 'IRON_ORE'
  - 'COAL_ORE'
  - 'LAPIS_ORE'
  - 'DIAMOND_ORE'
  - 'REDSTONE_ORE'
  - 'EMERALD_ORE'
  - 'QUARTZ'
  ALL_FARM_FULL_STAGE:
  - 'WHEAT 7'
  - 'CARROTS 7'
  - 'POTATOES 7'
  - 'BEETROOTS 3'
  - 'PUMPKIN_STEM 7'
  - 'MELON_STEM 7'
  - 'COCOA 2'
  - 'NETHER_WART 3'
  - 'SWEET_BERRY_BUSH 2'
  - 'SWEET_BERRY_BUSH 3'
  ALL_BOW:
  - 'BOW'
  ALL_ARMOR:
  - 'CHAINMAIL_HELMET'
  - 'IRON_HELMET'
  #- 'GOLDEN_HELMET'
  - 'DIAMOND_HELMET'
  - 'LEATHER_HELMET'
  - 'CHAINMAIL_CHESTPLATE'
  - 'IRON_CHESTPLATE'
  #- 'GOLDEN_CHESTPLATE'
  - 'DIAMOND_CHESTPLATE'
  - 'LEATHER_CHESTPLATE'
  - 'CHAINMAIL_LEGGINGS'
  - 'IRON_LEGGINGS'
  #- 'GOLDEN_LEGGINGS'
  - 'DIAMOND_LEGGINGS'
  - 'LEATHER_LEGGINGS'
  - 'CHAINMAIL_BOOTS'
  - 'IRON_BOOTS'
  #- 'GOLDEN_BOOTS'
  - 'DIAMOND_BOOTS'
  - 'LEATHER_BOOTS'
  - 'CHAINMAIL_HELMET'
  - 'IRON_HELMET'
  #- 'GOLDEN_HELMET'
  - 'DIAMOND_HELMET'
  - 'LEATHER_HELMET'
  ALL_HELMET:
  - 'CHAINMAIL_HELMET'
  - 'IRON_HELMET'
  #- 'GOLDEN_HELMET'
  - 'DIAMOND_HELMET'
  - 'LEATHER_HELMET'
  ALL_CHESTPLATE:
  - 'CHAINMAIL_CHESTPLATE'
  - 'IRON_CHESTPLATE'
  #- 'GOLDEN_CHESTPLATE'
  - 'DIAMOND_CHESTPLATE'
  - 'LEATHER_CHESTPLATE'
  ALL_LEGGINGS:
  - 'CHAINMAIL_LEGGINGS'
  - 'IRON_LEGGINGS'
  #- 'GOLDEN_LEGGINGS'
  - 'DIAMOND_LEGGINGS'
  - 'LEATHER_LEGGINGS'
  ALL_BOOTS:
  - 'CHAINMAIL_BOOTS'
  - 'IRON_BOOTS'
  #- 'GOLDEN_BOOTS'
  - 'DIAMOND_BOOTS'
  - 'LEATHER_BOOTS'
  ALL_SWORD:
  - 'WOODEN_SWORD'
  - 'STONE_SWORD'
  - 'IRON_SWORD'
  #- 'GOLDEN_SWORD'
  - 'DIAMOND_SWORD'
  ALL_PICKAXE:
  - 'WOODEN_PICKAXE'
  - 'STONE_PICKAXE'
  - 'IRON_PICKAXE'
  #- 'GOLDEN_PICKAXE'
  - 'DIAMOND_PICKAXE'
  ALL_AXE:
  - 'WOODEN_AXE'
  - 'STONE_AXE'
  - 'IRON_AXE'
  #- 'GOLDEN_AXE'
  - 'DIAMOND_AXE'
  ALL_SHOVEL:
  - 'WOODEN_SHOVEL'
  - 'STONE_SHOVEL'
  - 'IRON_SHOVEL'
  #- 'GOLDEN_SHOVEL'
  - 'DIAMOND_SHOVEL'
  ALL_HOE:
  - 'WOODEN_HOE'
  - 'STONE_HOE'
  - 'IRON_HOE'
  #- 'GOLDEN_HOE'
  - 'DIAMOND_HOE'
  ALL_SHOVEL:
  - 'WOODEN_SHOVEL'
  - 'STONE_SHOVEL'
  - 'IRON_SHOVEL'
  #- 'GOLDEN_SHOVEL'
  - 'DIAMOND_SHOVEL'
  ALL_GEM:
  - 'MAGMA_CREAM'